inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Include:
    - "**/*.cap"
    - "**/Gemfile"
    - "**/Rakefile"
    - "appsignal.gemspec"
  Exclude:
    - "pkg/**/*"
    - "tmp/**/*"
    - "gemfiles/vendor/**/*"
    - "vendor/**/*"
    - "benchmark.rake"
    - "spec/integration/diagnose/**/*"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MissingRespondToMissing:
  Exclude:
    - "lib/appsignal/extension.rb"
    - "lib/appsignal/transaction.rb"

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/WordArray:
  Enabled: false

Naming/FileName:
  Exclude:
    - "ext/Rakefile"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

# Metrics/LineLength:
#   Max: 80
